brand_name = ['life', 'only',
              'fratini',
              'zink london',
              'kraus',
              'rare',
              'van heusen',
              'stop',
              'cover story',
              'infuse',
              'allen solly',
              'altlife',
              'madame',
              'iti',
              'and',
              'faballey',
              'latin quarters',
              'sera',
              'adidas',
              'pepe',
              'indya',
              'juniper',
              'lovegen',
              'forever new',
              'magre',
              'insense',
              'calvin klein underwear',
              'reebok',
              'marie claire',
              'enamor',
              'vero moda',
              'spykar',
              'dolce crudo',
              'global desi',
              'crimsoune club',
              'haute curry',
              'proline',
              'puma',
              'ivy',
              'vh flex',
              'myshka',
              '109f',
              'w',
              'gipsy',
              'samshek',
              'is.u',
              'kami kubi',
              'varanga',
              'de moza',
              'u.s. polo assn.',
              'janasya',
              'kashish',
              'pepe kids',
              'erotissch',
              'biba',
              'ed hardy',
              'mystere paris',
              'louis philippe',
              'mimosa',
              'soie',
              'sweet dreams',
              'imara',
              'charchit',
              'athome',
              'indian terrain',
              'yuris',
              'suti',
              'sanaa',
              'ziyaa',
              'mothercare',
              'jack and jones',
              'aurelia',
              'neerus',
              'amukti',
              'fusion beats',
              'gas']

colour = ['indigo',
          'yellow',
          'off white',
          'black',
          'stone',
          'light blue',
          'white',
          'blush',
          'navy',
          'pink',
          'orange',
          'blue',
          'maroon',
          'mid stone',
          'olive',
          'ecru',
          'green',
          'pink mix',
          'dark brown',
          'sage',
          'mustard',
          'natural',
          'grey',
          'blue denim',
          'red',
          'baby pink',
          'lilac',
          'aubergine',
          'tan',
          'brown',
          'pista green',
          'dark blue',
          'powder blue',
          'misty lilac',
          'wine',
          'multi',
          'bottle green',
          'peach',
          'dusty pink',
          'charcoal',
          'mauve',
          'lavender',
          'dk indigo',
          'cream',
          'mint',
          'purple',
          'royal blue',
          'rose',
          'sky blue',
          'teal',
          'ice',
          'gold',
          'lime green',
          'black mix',
          'ice blue',
          'old rose',
          'print',
          'ocean',
          'chocolate',
          'grey melange',
          'dark grey',
          'magenta',
          'burgundy',
          'aqua',
          'denimex',
          'anthra melange',
          'apple green',
          'dark green',
          'stonewash blue',
          'rust',
          'khaki',
          'ltgrey',
          'red mix',
          'mid blue',
          'ivory',
          'coral',
          'air force',
          'midstone',
          'blue mix light',
          'berry',
          'fuschia',
          'anthra',
          'beige',
          'honey',
          'brick',
          'cloud',
          'biscuit',
          'cobalt',
          'sea blue',
          'checks',
          'lemon',
          '106_multi',
          'deep navy',
          'denim indigo dark',
          'pale peach',
          'plum',
          'linen',
          'porcelain',
          'pale yellow',
          'emerald',
          'butter',
          'turquoise',
          'major brown',
          'double black',
          'moss green',
          'dark pink',
          'carbon',
          'nude',
          'burnt orange',
          'light olive',
          'sea green',
          'mixed darks',
          'rosewood',
          'peacock',
          'tint',
          'camel',
          'glaze',
          'buff',
          'true navy',
          'grey pink',
          'denim',
          'gray',
          'ginger snap',
          'ribbon red',
          'fuchsia',
          'streaky brown',
          'bleach',
          'ink blue',
          'twill mud',
          'salmon',
          'flash',
          'teal_green',
          'mid used',
          'shocking pink',
          'light brown',
          'champagne',
          'brown mix',
          'navy marl',
          'sunset',
          'marine green',
          'legend blue',
          'aviator',
          'leaf green',
          'retro navy',
          'candy',
          'cherry',
          'mastic white',
          'mullet',
          'herb green',
          'mango',
          'silver',
          'blue melange',
          'island blue',
          'green mix',
          'birch',
          'shrimp',
          'ultramarine',
          'walnut',
          'taupe',
          'flamingo',
          'coffee',
          'off_white',
          'sky',
          'merc black',
          'blasted navy',
          'spice',
          'dark olive',
          'graphite',
          'chalk pink',
          'crystal',
          'orange mix',
          'electric',
          'silver grey',
          'indiaink',
          'light vintage',
          'dusty rose',
          'fawn',
          'fluid_olive',
          'ink',
          'dave grey',
          'carrot',
          'cider',
          'black rinse',
          'olive bleached',
          'black grey',
          'acid green',
          'mastic thread dark stone',
          'grey cast',
          'jade',
          'maple',
          'sand',
          'mixed pastels',
          'imperial yellow',
          'smoke',
          'steel',
          'thistle',
          'mouse',
          'soft grey',
          'dusty peach',
          'rose gold',
          'light mauve',
          'lt tan',
          'vintage blue',
          'terracotta',
          'bluesteel',
          'misty blue',
          'seagreen',
          'tomato',
          'onion_pink',
          'marine',
          'light orange',
          'lime',
          'pale pink',
          'raspberry',
          'pistachio',
          'ochre']

category = ['a-line dress',
            'blouson dress',
            'regular top',
            'dress',
            'jeans',
            'regular dress',
            'flared dress',
            'shift dress',
            't-shirt',
            'top',
            'shirt',
            'formal shirt',
            'regular woven top',
            'trousers',
            'loungewear short set',
            'active wear track pants',
            'bodycon dress',
            'casual wear trousers',
            'casual trousers',
            'regular dresses',
            'woven top',
            'straight top',
            'fit and flare dress',
            'casual shirt',
            'strappy dress',
            'tights',
            'formal pants'
            ]
