def generate_annotations(items):
    annotations = []
    for item in items:
        for text in items:
            if text != item:
                continue
            idx = item.lower().find(text.lower())
            if idx != -1:
                annotations.append((text, {"entities": [(idx, idx + len(text), "Brand" if item in brands else "Color")]}))
    return annotations
# Example usage for brands
brands = ['life',
          'only',
          'fratini',
          'zink london',
          'kraus',
          'rare',
          'van heusen',
          'stop',
          'zink z',
          'cover story',
          'infuse',
          'allen solly',
          'altlife',
          'madame',
          'iti',
          'levis',
          'and',
          'faballey',
          'latin quarters',
          'sera',
          'adidas',
          'pepe',
          'indya',
          'juniper',
          'lovegen',
          'vero moda',
          'forever new',
          'magre',
          'insense',
          'calvin klein underwear',
          'reebok',
          'marie claire',
          'enamor',
          'spykar',
          'get wrapped',
          'campus sutra',
          'dolce crudo',
          'emblaze',
          'global desi',
          'jealous 21',
          'jockey',
          'crimsoune club',
          'haute curry',
          'proline',
          'puma',
          'ivy',
          'vh flex',
          'myshka',
          'femina flaunt',
          'w',
          '109f',
          'gipsy',
          'samshek',
          'is.u',
          'miss chase',
          'ira soleil',
          'fila',
          'kami kubi',
          'travel blue',
          'varanga',
          'de moza',
          'u.s. polo assn.',
          'vip',
          'janasya',
          'skechers',
          'lee cooper',
          'aarke',
          'kashish',
          'pepe kids',
          'kenneth cole',
          'zingg',
          'ayesha',
          'elliza donatein',
          'erotissch',
          'biba',
          'ed hardy',
          'black panther',
          'mystere paris',
          'monte carlo',
          'louis philippe',
          'mimosa',
          'hidesign',
          'soie',
          'sweet dreams',
          'giordano',
          'karrot',
          'alcis',
          'imara',
          'charchit',
          'athome',
          'disha patani for glam lifestyle',
          'allen solly tribe',
          'ariana',
          'lavie',
          'rukootina',
          'indian terrain',
          'yuris',
          'duke',
          'high star',
          'suti',
          'fastrack',
          'sanaa',
          'ziyaa',
          'mothercare',
          'jack and jones',
          'aurelia',
          'shaya by caratlane',
          'neerus',
          'amukti',
          'vastranand',
          'varkala silk sarees',
          'fusion beats',
          'ritu kumar',
          'emporio armani',
          'gas',
          'arteastri']

brand_annotations = generate_annotations(brands)

# Example usage for colors
colors = [
    "Red", "Blue", "Green", "Yellow"
]
color_annotations = generate_annotations(colors)

# Combine the annotations
TRAINING_DATA = brand_annotations + color_annotations

print(TRAINING_DATA)


